plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'com.example.road.to.effective.snapshot.testing.lazycolumnscreen_previews'
    compileSdk 36

    defaultConfig {
        minSdk 24

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = '21'
    }

    buildFeatures {
        // Enables Jetpack Compose for this module
        compose true
    }
    lint {
        targetSdk 36
    }
    testOptions {
        targetSdk 36
    }

    experimentalProperties["android.experimental.enableScreenshotTest"] = true
}

dependencies {
    implementation project(":lazycolumnscreen")
    implementation 'androidx.core:core-ktx:1.17.0'

    // Jetpack Compose
    screenshotTestImplementation platform('androidx.compose:compose-bom:2026.06.01')
    screenshotTestImplementation "androidx.compose.ui:ui-tooling"
}