package sergio.sastre.composable.preview.scanner.core.scanner

import io.github.classgraph.ClassGraph
import io.github.classgraph.ScanResult
import sergio.sastre.composable.preview.scanner.core.scanresult.RequiresLargeHeap
import sergio.sastre.composable.preview.scanner.core.scanresult.filter.ScanResultFilter
import java.io.File
import java.io.InputStream

/**
 * Core Component to scan for Previews
 */
abstract class ComposablePreviewScanner<T>(
    private val findComposableWithPreviewsInClass: ComposablesWithPreviewsFinder<T>
) {

    private var updatedClassGraph = ClassGraph()
        .enableClassInfo()
        .enableMethodInfo()
        .enableAnnotationInfo()
        .enableMemoryMapping()

    /**
     * Scan for previews in all packages, including those of external dependencies.
     */
    @RequiresLargeHeap
    fun scanAllPackages(): ScanResultFilter<T> {
        return ScanResultFilter(updatedClassGraph.scan(), findComposableWithPreviewsInClass)
    }

    /**
     * Scan for previews in the given packageTrees
     *
     * @param packageTrees where we want to scan for previews
     */
    fun scanPackageTrees(vararg packageTrees: String): ScanResultFilter<T> {
        if (packageTrees.isEmpty()) {
            throw IllegalArgumentException("packages must not be empty. For that, use scanAllPackages() instead")
        }
        updatedClassGraph = updatedClassGraph.acceptPackages(*packageTrees)
        return ScanResultFilter(updatedClassGraph.scan(), findComposableWithPreviewsInClass)
    }

    /**
     * Scan for previews in the given file
     *
     * @param jsonFile a json file that was generated by using ScanResultDump.dumpScanResultToFile(fileName)
     */
    fun scanFile(jsonFile: File): ScanResultFilter<T> {
        val scanResult = ScanResult.fromJSON(jsonFile.bufferedReader().use { it.readLine() })
        return ScanResultFilter(scanResult, findComposableWithPreviewsInClass)
    }

    /**
     * Scan for previews in the given InputStream.
     *
     * @param inputStream to support accessible by instrumentation tests, like getInstrumentation().context.assets.open(fileName).
     * Such file was generated previously by using ScanResultDump.dumpScanResultToFileInAssets(fileName)
     *
     */
    fun scanFile(inputStream: InputStream): ScanResultFilter<T> {
        val scanResult = ScanResult.fromJSON(inputStream.bufferedReader().use { it.readLine() })
        return ScanResultFilter(scanResult, findComposableWithPreviewsInClass)
    }
}