plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'io.github.takahirom.roborazzi'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'com.example.road.to.effective.snapshot.testing.lazycolumnscreen.roborazzi'
    compileSdk 36

    defaultConfig {
        testApplicationId "com.example.road.to.effective.snapshot.testing"
        minSdk 23

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            pseudoLocalesEnabled true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = '21'
    }

    

    buildFeatures {
        // Enables Jetpack Compose for this module
        compose true
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
            all {
                // Do not run out of memory when running Roborazzi tests for different api levels
                jvmArgs '-Xmx1g'

                // Enable running tests in parallel
                if (project.hasProperty("parallel")) {
                    maxParallelForks = Runtime.runtime.availableProcessors() / 2
                }

                // Enable hardware rendering to display shadows and elevation. Still experimental
                // Supported only on API 28+
                systemProperty 'robolectric.pixelCopyRenderMode', 'hardware'
            }
        }
        targetSdk 36
    }
    lint {
        targetSdk 36
    }
}

dependencies {
    implementation project(':lazycolumnscreen')

    implementation "androidx.navigation:navigation-compose:2.9.5"

    // Jetpack Compose
    testImplementation platform('androidx.compose:compose-bom:2026.06.01')
    testImplementation "androidx.compose.material:material"

    testImplementation "org.robolectric:robolectric:4.16.1"
    testImplementation 'com.github.sergio-sastre.AndroidUiTestingUtils:utils:2.10.0'
    testImplementation 'com.github.sergio-sastre.AndroidUiTestingUtils:robolectric:2.10.0'
    testImplementation 'com.github.sergio-sastre.AndroidUiTestingUtils:roborazzi:2.10.0'
}
